&copy; 2020<br><br>
Sandy Hardian Susanto Herho dan Dasapta Erwin Irawan

# Dasar - dasar pemrograman

## Aritmatika

In [1]:
1 + 2

[1] 3

In [2]:
5 - 3

[1] 2

In [3]:
5.25 + 3.95

[1] 9.2

In [4]:
3 * 2

[1] 6

In [5]:
15 / 2

[1] 7.5

In [6]:
2 ^ 3

[1] 8

In [7]:
# operator modulus

15/2 

[1] 7.5

In [8]:
15 %% 2

[1] 1

In [9]:
# urutan operasi
15 * 20 + 50 / 2

[1] 325

In [10]:
15 * 20 + (50 / 2)

[1] 325

In [11]:
15 * (20 + 50) / 2

[1] 525

## Variabel

In [12]:
# komentar
v <- 10

In [13]:
print(v)

[1] 10


In [14]:
v

[1] 10

In [15]:
uang <- 100000

In [16]:
uang

[1] 1e+05

In [17]:
tiket.bioskop <- 2e5 # paling sering digunakan di komunitas R
tiket.bioskop

[1] 2e+05

In [18]:
tiketBioskop <- 2.05e5
tiketBioskop

[1] 205000

In [19]:
tiket_bioskop <-2.1e5
tiket_bioskop

[1] 210000

In [20]:
popcorn <- 5e4
popcorn

[1] 50000

In [21]:
tiket.bioskop <- tiket.bioskop + popcorn + 2e4
print(tiket.bioskop)

[1] 270000


## Tipe - tipe data

### Numerik

In [22]:
b <- 2
b

[1] 2

In [23]:
d <- 3.5
d

[1] 3.5

In [24]:
class(d)

[1] "numeric"

In [25]:
class(b)

[1] "numeric"

Integer dan float di R dianggap sebagai tipe data numerik

### Logical

In [26]:
TRUE

[1] TRUE

In [27]:
FALSE

[1] FALSE

In [28]:
T

[1] TRUE

In [29]:
F

[1] FALSE

In [30]:
a <- TRUE
a

[1] TRUE

In [31]:
class(a)

[1] "logical"

### Character

In [32]:
"Halo"

[1] "Halo"

In [33]:
'Halo'

[1] "Halo"

In [34]:
txt <- "Hello world!"
print(txt)

[1] "Hello world!"


In [35]:
class(txt)

[1] "character"

## Vektor

In [36]:
num <- c(1,2,3,4,5)

In [37]:
class(num)

[1] "numeric"

In [38]:
txt <- c('a', 'b', 'c')
txt

[1] "a" "b" "c"

In [39]:
class(txt)

[1] "character"

In [40]:
l <- c(T,F)
l

[1]  TRUE FALSE

In [41]:
class(l)

[1] "logical"

In [42]:
v1 <- c(TRUE, 10, 20)
v1

[1]  1 10 20

In [43]:
class(v1) # logical dikonversi menjadi numeric

[1] "numeric"

In [44]:
v2 <- c('a', 'b', 20)
v2

[1] "a"  "b"  "20"

In [45]:
class(v2) # numeric dikonversi menjadi character

[1] "character"

In [46]:
v3 <- c(TRUE, 128, 'Meteorologi')
v3

[1] "TRUE"        "128"         "Meteorologi"

In [47]:
class(v3) # logical & numeric dikonversi menjadi character

[1] "character"

In [48]:
# names : metode penamaaan vektor (metode 1) 
hari <- c(1,2,3,4,5,6,7)
hari

[1] 1 2 3 4 5 6 7

In [49]:
names(hari) <- c('sen', 'sel', 'rab', 'kam', 'jum', 'sab', 'min')

In [50]:
hari

sen sel rab kam jum sab min 
  1   2   3   4   5   6   7

In [51]:
# names : metode penamaaan vektor (metode 2)
b <-  c('sen', 'sel', 'rab', 'kam', 'jum', 'sab', 'min')
names(hari) <- b
hari

sen sel rab kam jum sab min 
  1   2   3   4   5   6   7

In [52]:
hari['sen']

sen 
  1

In [53]:
hari[1]

sen 
  1

## Operasi - operasi vektor

In [54]:
v1 <- c(1,2,3,4,5)
v2 <- c(6,7,8,9,10)

In [55]:
v1 + v2 # element-by-element

[1]  7  9 11 13 15

In [56]:
v1 - v2

[1] -5 -5 -5 -5 -5

In [57]:
v1 * v2

[1]  6 14 24 36 50

In [58]:
v2 / v2

[1] 1 1 1 1 1

In [59]:
sum(v1) # jumlah seluruh v1

[1] 15

In [60]:
mean(v1) # rata2 v1

[1] 3

In [61]:
sd(v1) # std v1

[1] 1.581139

In [62]:
max(v2)

[1] 10

In [63]:
min(v2)

[1] 6

In [64]:
prod(v1) # mengalikan seluruh elemen di vektor 

[1] 120

In [65]:
prod(v2)

[1] 30240

In [66]:
b <- sum(v1)
print(b)

[1] 15


## Operator - operator perbandingan

In [67]:
4 > 5

[1] FALSE

In [68]:
7 > 4

[1] TRUE

In [69]:
10 >= 5

[1] TRUE

In [70]:
7 <= 5

[1] FALSE

In [71]:
8 == 8

[1] TRUE

In [72]:
7 != 15

[1] TRUE

In [73]:
7 != 7

[1] FALSE

In [74]:
# Operator perbandingan pada vektor
v <- c(1,2,3,4,5)
v < 2

[1]  TRUE FALSE FALSE FALSE FALSE

In [75]:
v == 3

[1] FALSE FALSE  TRUE FALSE FALSE

In [76]:
v2 <- c(10,20,30,40,50)
v2

[1] 10 20 30 40 50

In [77]:
v < v2

[1] TRUE TRUE TRUE TRUE TRUE

## Pengindeksan dan pemotongan vektor

In [78]:
v1 <- c(10,20,30,40,50)
v2 <- c('a', 'b', 'c', 'd', 'e')

In [79]:
v1[2] # pengindeksan dimulai dari 1

[1] 20

In [80]:
v1[5]

[1] 50

In [81]:
v2[c(3,4,5)]

[1] "c" "d" "e"

In [82]:
v3 <- c(1,2,3,4,5,6,7,8,9,10)
v3[7:10]

[1]  7  8  9 10

In [83]:
v3[3:5]

[1] 3 4 5

In [84]:
b <- c(1,2,3,4,5,6)
names(b) <- c('I', 'G', 'D', 'O', 'R', 'E')
b

I G D O R E 
1 2 3 4 5 6

In [85]:
b[2]

G 
2

In [86]:
b['G']

G 
2

In [87]:
b[c(2,3)]

G D 
2 3

In [88]:
b[c('G', 'D')]

G D 
2 3

In [89]:
# Operator perbandingan
b

I G D O R E 
1 2 3 4 5 6

In [90]:
b[b>3]

O R E 
4 5 6

In [91]:
e <-  b > 3

In [92]:
b[e]

O R E 
4 5 6

# Matriks

## Mendefinisikan matriks

In [93]:
b <- 1:10
b

[1]  1  2  3  4  5  6  7  8  9 10

In [94]:
matrix(b) # 10 x 1

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [95]:
matrix(b, nrow=2, ncol= 5) # by column

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [96]:
matrix(b, nrow=2, ncol= 5, byrow = T) # by row

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [97]:
matrix(1:12, nrow = 4, byrow=TRUE) # 4 x 3 by row

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [98]:
# Mendefinisikan matriks dari vektor
fb <- c(250,255,260,263,265) # bayangkan sebagai harga saham
ms <- c(455,460,465,479, 470)

In [99]:
saham <- c(fb, ms)
saham

[1] 250 255 260 263 265 455 460 465 479 470

In [100]:
matriks.saham <- matrix(saham, nrow=2, byrow=T)
matriks.saham

[,1] [,2] [,3] [,4] [,5]
[1,] 250  255  260  263  265 
[2,] 455  460  465  479  470

In [101]:
# Menamakan baris dan kolom

In [102]:
hari <- c('sen', 'sel', 'rab', 'kam', 'jum')
perusahaan <- c('fb', 'ms')

In [103]:
colnames(matriks.saham) <- hari
rownames(matriks.saham) <- perusahaan

In [104]:
matriks.saham

sen sel rab kam jum
fb 250 255 260 263 265
ms 455 460 465 479 470

## Aritmatika matriks

In [105]:
mat <- matrix(1:25, nrow=5, byrow=T)
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [106]:
mat * mat # element-by-element

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [107]:
mat / mat

[,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1   
[2,] 1    1    1    1    1   
[3,] 1    1    1    1    1   
[4,] 1    1    1    1    1   
[5,] 1    1    1    1    1

In [108]:
mat^2

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    9   16   25 
[2,]  36   49   64   81  100 
[3,] 121  144  169  196  225 
[4,] 256  289  324  361  400 
[5,] 441  484  529  576  625

In [109]:
1 / mat

[,1]       [,2]       [,3]       [,4]       [,5]      
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000
[2,] 0.16666667 0.14285714 0.12500000 0.11111111 0.10000000
[3,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
[4,] 0.06250000 0.05882353 0.05555556 0.05263158 0.05000000
[5,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000

In [110]:
# Operator perbandingan di matriks

In [111]:
mat > 10

[,1]  [,2]  [,3]  [,4]  [,5] 
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE

In [112]:
mat[mat > 10]

[1] 11 16 21 12 17 22 13 18 23 14 19 24 15 20 25

In [113]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [114]:
# Perkalian matriks
mat %*% mat

[,1] [,2] [,3] [,4] [,5]
[1,]  215  230  245  260  275
[2,]  490  530  570  610  650
[3,]  765  830  895  960 1025
[4,] 1040 1130 1220 1310 1400
[5,] 1315 1430 1545 1660 1775

## Operasi - operasi di matriks

In [115]:
# Mendefinisikan matriks dari vektor
fb <- c(250,255,260,263,265)
ms <- c(455,460,465,479, 470)
saham <- c(fb, ms)
matriks.saham <- matrix(saham, nrow=2, byrow=T)
colnames(matriks.saham) <- c('sen', 'sel', 'rab', 'kam', 'jum')
rownames(matriks.saham) <-  c('fb', 'ms')
matriks.saham

sen sel rab kam jum
fb 250 255 260 263 265
ms 455 460 465 479 470

In [116]:
colSums(matriks.saham) # penjumlahan pada kolom

sen sel rab kam jum 
705 715 725 742 735

In [117]:
rowSums(matriks.saham)

fb   ms 
1293 2329

In [118]:
rowMeans(matriks.saham)

fb    ms 
258.6 465.8

In [119]:
colMeans(matriks.saham)

sen   sel   rab   kam   jum 
352.5 357.5 362.5 371.0 367.5

In [120]:
# Menambahkan kolom dan baris ke matriks

In [121]:
google <- c(175,180,185,195,190)
saham.int <- rbind(matriks.saham, google)
saham.int

sen sel rab kam jum
fb     250 255 260 263 265
ms     455 460 465 479 470
google 175 180 185 195 190

In [122]:
# Menambahkan kolom ke matriks
rata2 <- rowMeans(saham.int)
rata2

fb     ms google 
 258.6  465.8  185.0

In [123]:
saham.int <- cbind(saham.int, rata2)
saham.int

sen sel rab kam jum rata2
fb     250 255 260 263 265 258.6
ms     455 460 465 479 470 465.8
google 175 180 185 195 190 185.0

## Seleksi dan pengindeksan matriks

In [124]:
v <- c(10,20,30,40,50)
v

[1] 10 20 30 40 50

In [125]:
v[3]

[1] 30

In [126]:
mat <- matrix(1:25, nrow=5, byrow=T)
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [127]:
mat[1,] # baris 1, seluruh kolom

[1] 1 2 3 4 5

In [128]:
mat[2,3]

[1] 8

In [129]:
mat[3,4]

[1] 14

In [130]:
mat[,3]

[1]  3  8 13 18 23

In [131]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [132]:
mat[,5]

[1]  5 10 15 20 25

In [133]:
mat[1:3,] # baris 1 sampai 3

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15

In [134]:
mat[,4:5] # kolom 4 hingga 5

[,1] [,2]
[1,]  4    5  
[2,]  9   10  
[3,] 14   15  
[4,] 19   20  
[5,] 24   25

In [135]:
mat[1:2, 1:3] # baris 1 sampai 2, kolom 1 sampai 3

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 6    7    8

In [136]:
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [137]:
mat[3:5, 3:5]

[,1] [,2] [,3]
[1,] 13   14   15  
[2,] 18   19   20  
[3,] 23   24   25

## Fungsi `factor`

In [138]:
vek.warna <- c('merah', 'hijau', 'biru', 'merah', 'merah', 'hijau', 'biru')

In [139]:
vek.warna

[1] "merah" "hijau" "biru"  "merah" "merah" "hijau" "biru"

In [140]:
fact.warna <- factor(vek.warna, ordered=T, levels=c('merah', 'hijau', 'biru'))
fact.warna

[1] merah hijau biru  merah merah hijau biru 
Levels: merah < hijau < biru

In [141]:
summary(fact.warna)

merah hijau  biru 
    3     2     2

In [142]:
summary(vek.warna)

   Length     Class      Mode 
        7 character character 

# Data Frame

## Pengenalan

Kita banyak menggunakan data frame di dalam kegiatan analisis data, karena matriks hanya mampu menampung tipe data yang seragam.

In [143]:
state.x77 # built-in df

Population Income Illiteracy Life Exp Murder HS Grad Frost
Alabama         3615      3624   2.1        69.05    15.1   41.3     20  
Alaska           365      6315   1.5        69.31    11.3   66.7    152  
Arizona         2212      4530   1.8        70.55     7.8   58.1     15  
Arkansas        2110      3378   1.9        70.66    10.1   39.9     65  
California     21198      5114   1.1        71.71    10.3   62.6     20  
Colorado        2541      4884   0.7        72.06     6.8   63.9    166  
Connecticut     3100      5348   1.1        72.48     3.1   56.0    139  
Delaware         579      4809   0.9        70.06     6.2   54.6    103  
Florida         8277      4815   1.3        70.66    10.7   52.6     11  
Georgia         4931      4091   2.0        68.54    13.9   40.6     60  
Hawaii           868      4963   1.9        73.60     6.2   61.9      0  
Idaho            813      4119   0.6        71.87     5.3   59.5    126  
Illinois       11197      5107   0.9        70.14    10.3   52.6    127  
Indiana         5313      4458   0.7        70.88     7.1   52.9    122  
Iowa            2861      4628   0.5        72.56     2.3   59.0    140  
Kansas          2280      4669   0.6        72.58     4.5   59.9    114  
Kentucky        3387      3712   1.6        70.10    10.6   38.5     95  
Louisiana       3806      3545   2.8        68.76    13.2   42.2     12  
Maine           1058      3694   0.7        70.39     2.7   54.7    161  
Maryland        4122      5299   0.9        70.22     8.5   52.3    101  
Massachusetts   5814      4755   1.1        71.83     3.3   58.5    103  
Michigan        9111      4751   0.9        70.63    11.1   52.8    125  
Minnesota       3921      4675   0.6        72.96     2.3   57.6    160  
Mississippi     2341      3098   2.4        68.09    12.5   41.0     50  
Missouri        4767      4254   0.8        70.69     9.3   48.8    108  
Montana          746      4347   0.6        70.56     5.0   59.2    155  
Nebraska        1544      4508   0.6        72.60     2.9   59.3    139  
Nevada           590      5149   0.5        69.03    11.5   65.2    188  
New Hampshire    812      4281   0.7        71.23     3.3   57.6    174  
New Jersey      7333      5237   1.1        70.93     5.2   52.5    115  
New Mexico      1144      3601   2.2        70.32     9.7   55.2    120  
New York       18076      4903   1.4        70.55    10.9   52.7     82  
North Carolina  5441      3875   1.8        69.21    11.1   38.5     80  
North Dakota     637      5087   0.8        72.78     1.4   50.3    186  
Ohio           10735      4561   0.8        70.82     7.4   53.2    124  
Oklahoma        2715      3983   1.1        71.42     6.4   51.6     82  
Oregon          2284      4660   0.6        72.13     4.2   60.0     44  
Pennsylvania   11860      4449   1.0        70.43     6.1   50.2    126  
Rhode Island     931      4558   1.3        71.90     2.4   46.4    127  
South Carolina  2816      3635   2.3        67.96    11.6   37.8     65  
South Dakota     681      4167   0.5        72.08     1.7   53.3    172  
Tennessee       4173      3821   1.7        70.11    11.0   41.8     70  
Texas          12237      4188   2.2        70.90    12.2   47.4     35  
Utah            1203      4022   0.6        72.90     4.5   67.3    137  
Vermont          472      3907   0.6        71.64     5.5   57.1    168  
Virginia        4981      4701   1.4        70.08     9.5   47.8     85  
Washington      3559      4864   0.6        71.72     4.3   63.5     32  
West Virginia   1799      3617   1.4        69.48     6.7   41.6    100  
Wisconsin       4589      4468   0.7        72.48     3.0   54.5    149  
Wyoming          376      4566   0.6        70.29     6.9   62.9    173  
               Area  
Alabama         50708
Alaska         566432
Arizona        113417
Arkansas        51945
California     156361
Colorado       103766
Connecticut      4862
Delaware         1982
Florida         54090
Georgia         58073

In [144]:
USPersonalExpenditure

1940   1945   1950  1955 1960 
Food and Tobacco    22.200 44.500 59.60 73.2 86.80
Household Operation 10.500 15.500 29.00 36.5 46.20
Medical and Health   3.530  5.760  9.71 14.0 21.10
Personal Care        1.040  1.980  2.45  3.4  5.40
Private Education    0.341  0.974  1.80  2.6  3.64

In [145]:
# Mengetahui daftar built-in df
data()

In [146]:
head(state.x77) # 6 baris pertama

Population Income Illiteracy Life Exp Murder HS Grad Frost Area  
Alabama     3615      3624   2.1        69.05    15.1   41.3     20    50708
Alaska       365      6315   1.5        69.31    11.3   66.7    152   566432
Arizona     2212      4530   1.8        70.55     7.8   58.1     15   113417
Arkansas    2110      3378   1.9        70.66    10.1   39.9     65    51945
California 21198      5114   1.1        71.71    10.3   62.6     20   156361
Colorado    2541      4884   0.7        72.06     6.8   63.9    166   103766

In [147]:
tail(state.x77) # 6 baris terakhir

Population Income Illiteracy Life Exp Murder HS Grad Frost Area 
Vermont        472       3907   0.6        71.64    5.5    57.1    168    9267
Virginia      4981       4701   1.4        70.08    9.5    47.8     85   39780
Washington    3559       4864   0.6        71.72    4.3    63.5     32   66570
West Virginia 1799       3617   1.4        69.48    6.7    41.6    100   24070
Wisconsin     4589       4468   0.7        72.48    3.0    54.5    149   54464
Wyoming        376       4566   0.6        70.29    6.9    62.9    173   97203

In [148]:
str(state.x77) # struktur dari df

 num [1:50, 1:8] 3615 365 2212 2110 21198 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:50] "Alabama" "Alaska" "Arizona" "Arkansas" ...
  ..$ : chr [1:8] "Population" "Income" "Illiteracy" "Life Exp" ...


In [149]:
summary(state.x77) # sari statistik dari df berdasarkan kolom

   Population        Income       Illiteracy       Life Exp    
 Min.   :  365   Min.   :3098   Min.   :0.500   Min.   :67.96  
 1st Qu.: 1080   1st Qu.:3993   1st Qu.:0.625   1st Qu.:70.12  
 Median : 2838   Median :4519   Median :0.950   Median :70.67  
 Mean   : 4246   Mean   :4436   Mean   :1.170   Mean   :70.88  
 3rd Qu.: 4968   3rd Qu.:4814   3rd Qu.:1.575   3rd Qu.:71.89  
 Max.   :21198   Max.   :6315   Max.   :2.800   Max.   :73.60  
     Murder          HS Grad          Frost             Area       
 Min.   : 1.400   Min.   :37.80   Min.   :  0.00   Min.   :  1049  
 1st Qu.: 4.350   1st Qu.:48.05   1st Qu.: 66.25   1st Qu.: 36985  
 Median : 6.850   Median :53.25   Median :114.50   Median : 54277  
 Mean   : 7.378   Mean   :53.11   Mean   :104.46   Mean   : 70736  
 3rd Qu.:10.675   3rd Qu.:59.15   3rd Qu.:139.75   3rd Qu.: 81162  
 Max.   :15.100   Max.   :67.30   Max.   :188.00   Max.   :566432  

In [150]:
# mendefinisikan df
nama <- c('Agus', 'Sugio', 'Bayu', 'Atmo', 'Roy')
umur <- c(42,35,37,28,27)
kawin <- c(F,F,T,F,T)

In [151]:
data.frame(nama, umur, kawin)

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [152]:
df <- data.frame(nama, umur, kawin)
df

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [153]:
str(df)

'data.frame':	5 obs. of  3 variables:
 $ nama : Factor w/ 5 levels "Agus","Atmo",..: 1 5 3 2 4
 $ umur : num  42 35 37 28 27
 $ kawin: logi  FALSE FALSE TRUE FALSE TRUE


In [154]:
summary(df)

    nama        umur        kawin        
 Agus :1   Min.   :27.0   Mode :logical  
 Atmo :1   1st Qu.:28.0   FALSE:3        
 Bayu :1   Median :35.0   TRUE :2        
 Roy  :1   Mean   :33.8                  
 Sugio:1   3rd Qu.:37.0                  
           Max.   :42.0                  

## Seleksi dan pengindeksan Data Frame

In [155]:
df

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [156]:
df[3, ] # ambil baris ketiga

nama umur kawin
3 Bayu 37   TRUE

In [157]:
df[,1]

[1] Agus  Sugio Bayu  Atmo  Roy  
Levels: Agus Atmo Bayu Roy Sugio

In [158]:
df[,'nama']

[1] Agus  Sugio Bayu  Atmo  Roy  
Levels: Agus Atmo Bayu Roy Sugio

In [159]:
df[1:4, c('nama', 'umur')]

nama  umur
1 Agus  42  
2 Sugio 35  
3 Bayu  37  
4 Atmo  28

In [160]:
df$umur

[1] 42 35 37 28 27

In [161]:
df[,'umur']

[1] 42 35 37 28 27

In [162]:
# fungsi subset
df

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [163]:
subset(df,subset = kawin == T) 

nama umur kawin
3 Bayu 37   TRUE 
5 Roy  27   TRUE

In [164]:
subset(df, subset = umur > 30)

nama  umur kawin
1 Agus  42   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE

In [165]:
# Mengurutkan dataframe
urut.umur <- order(df['umur'])
urut.umur

[1] 5 4 2 3 1

In [166]:
df[urut.umur,]

nama  umur kawin
5 Roy   27    TRUE
4 Atmo  28   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
1 Agus  42   FALSE

In [167]:
umur.terbalik <- order(-df['umur'])
umur.terbalik

[1] 1 3 2 4 5

In [168]:
df[umur.terbalik,]

nama  umur kawin
1 Agus  42   FALSE
3 Bayu  37    TRUE
2 Sugio 35   FALSE
4 Atmo  28   FALSE
5 Roy   27    TRUE

In [169]:
urut.umur <- order(df$umur)
df[urut.umur, ]

nama  umur kawin
5 Roy   27    TRUE
4 Atmo  28   FALSE
2 Sugio 35   FALSE
3 Bayu  37    TRUE
1 Agus  42   FALSE

## Operasi - operasi data frame

### Mendefinisikan data frame

In [170]:
c1 <- 1:10
c2 <- letters[1:10]
print(c1)
print(c2)

 [1]  1  2  3  4  5  6  7  8  9 10
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j"


In [171]:
df <- data.frame(c1,c2)
df

c1 c2
1   1 a 
2   2 b 
3   3 c 
4   4 d 
5   5 e 
6   6 f 
7   7 g 
8   8 h 
9   9 i 
10 10 j

In [172]:
df <- data.frame(kolom1 = c1, kolom2 = c2) # nama kolom bisa kita ubah sesuka kita!
df

kolom1 kolom2
1   1     a     
2   2     b     
3   3     c     
4   4     d     
5   5     e     
6   6     f     
7   7     g     
8   8     h     
9   9     i     
10 10     j

### Mendapatkan info tentang data frame

In [173]:
nrow(df) # jumlah baris

[1] 10

In [174]:
ncol(df) # jumlah kolom

[1] 2

In [175]:
colnames(df)  # nama kolom

[1] "kolom1" "kolom2"

In [176]:
rownames(df) # nama baris

[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [177]:
str(df) # struktur data frame

'data.frame':	10 obs. of  2 variables:
 $ kolom1: int  1 2 3 4 5 6 7 8 9 10
 $ kolom2: Factor w/ 10 levels "a","b","c","d",..: 1 2 3 4 5 6 7 8 9 10


In [178]:
summary(df) # sari statistik

     kolom1          kolom2 
 Min.   : 1.00   a      :1  
 1st Qu.: 3.25   b      :1  
 Median : 5.50   c      :1  
 Mean   : 5.50   d      :1  
 3rd Qu.: 7.75   e      :1  
 Max.   :10.00   f      :1  
                 (Other):4  

### Referensi sel

In [179]:
df

kolom1 kolom2
1   1     a     
2   2     b     
3   3     c     
4   4     d     
5   5     e     
6   6     f     
7   7     g     
8   8     h     
9   9     i     
10 10     j

In [180]:
df[5,1]

[1] 5

In [181]:
df[[5,1]]

[1] 5

In [182]:
df[1,'kolom1']

[1] 1

In [183]:
df[5, 'kolom1']

[1] 5

In [184]:
df[[5,'kolom1']]

[1] 5

In [185]:
df[8,'kolom1'] <- -999 # mengubah nilai
df

kolom1 kolom2
1     1   a     
2     2   b     
3     3   c     
4     4   d     
5     5   e     
6     6   f     
7     7   g     
8  -999   h     
9     9   i     
10   10   j

In [186]:
df[[8,'kolom1']] <- 8
df

kolom1 kolom2
1   1     a     
2   2     b     
3   3     c     
4   4     d     
5   5     e     
6   6     f     
7   7     g     
8   8     h     
9   9     i     
10 10     j

### Referensi baris dan kolom

In [187]:
df[2,]

kolom1 kolom2
2 2      b

In [188]:
df[1:3,]

kolom1 kolom2
1 1      a     
2 2      b     
3 3      c

In [189]:
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [190]:
mtcars$mpg

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [191]:
mtcars[,1]

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [192]:
mtcars[,'mpg']

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [193]:
mtcars[['mpg']]

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4
[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7
[31] 15.0 21.4

In [194]:
mtcars[1] # indeks lokasi kolom:1, cara ini mereferensi kolom mpg sbg data frame

mpg 
Mazda RX4           21.0
Mazda RX4 Wag       21.0
Datsun 710          22.8
Hornet 4 Drive      21.4
Hornet Sportabout   18.7
Valiant             18.1
Duster 360          14.3
Merc 240D           24.4
Merc 230            22.8
Merc 280            19.2
Merc 280C           17.8
Merc 450SE          16.4
Merc 450SL          17.3
Merc 450SLC         15.2
Cadillac Fleetwood  10.4
Lincoln Continental 10.4
Chrysler Imperial   14.7
Fiat 128            32.4
Honda Civic         30.4
Toyota Corolla      33.9
Toyota Corona       21.5
Dodge Challenger    15.5
AMC Javelin         15.2
Camaro Z28          13.3
Pontiac Firebird    19.2
Fiat X1-9           27.3
Porsche 914-2       26.0
Lotus Europa        30.4
Ford Pantera L      15.8
Ferrari Dino        19.7
Maserati Bora       15.0
Volvo 142E          21.4

In [195]:
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [196]:
mtcars[c('mpg', 'cyl')]

mpg  cyl
Mazda RX4           21.0 6  
Mazda RX4 Wag       21.0 6  
Datsun 710          22.8 4  
Hornet 4 Drive      21.4 6  
Hornet Sportabout   18.7 8  
Valiant             18.1 6  
Duster 360          14.3 8  
Merc 240D           24.4 4  
Merc 230            22.8 4  
Merc 280            19.2 6  
Merc 280C           17.8 6  
Merc 450SE          16.4 8  
Merc 450SL          17.3 8  
Merc 450SLC         15.2 8  
Cadillac Fleetwood  10.4 8  
Lincoln Continental 10.4 8  
Chrysler Imperial   14.7 8  
Fiat 128            32.4 4  
Honda Civic         30.4 4  
Toyota Corolla      33.9 4  
Toyota Corona       21.5 4  
Dodge Challenger    15.5 8  
AMC Javelin         15.2 8  
Camaro Z28          13.3 8  
Pontiac Firebird    19.2 8  
Fiat X1-9           27.3 4  
Porsche 914-2       26.0 4  
Lotus Europa        30.4 4  
Ford Pantera L      15.8 8  
Ferrari Dino        19.7 6  
Maserati Bora       15.0 8  
Volvo 142E          21.4 4

### Menambahkan baris dan kolom

In [197]:
c1 <- c(10,20,30,40,50)
c2 <- letters[c(1:5)]
df <- data.frame(kol1=c1,kol2=c2)
df

kol1 kol2
1 10   a   
2 20   b   
3 30   c   
4 40   d   
5 50   e

In [198]:
df1 <- data.frame(kol1=128,kol2='Meteorologi')
df1

kol1 kol2       
1 128  Meteorologi

In [199]:
# menambahkan df1 ke df
df <- rbind(df,df1)
df

kol1 kol2       
1  10  a          
2  20  b          
3  30  c          
4  40  d          
5  50  e          
6 128  Meteorologi

In [200]:
c3 <- c(11:16)
c3

[1] 11 12 13 14 15 16

In [201]:
# menambahkan kolom ke df
df <- cbind(df,kol3=c3)
df

kol1 kol2        kol3
1  10  a           11  
2  20  b           12  
3  30  c           13  
4  40  d           14  
5  50  e           15  
6 128  Meteorologi 16

In [202]:
df$kol4 <- c(20,25,30,35,40,45)
df

kol1 kol2        kol3 kol4
1  10  a           11   20  
2  20  b           12   25  
3  30  c           13   30  
4  40  d           14   35  
5  50  e           15   40  
6 128  Meteorologi 16   45

In [203]:
df$kol5 <- df$kol1 * 2
df

kol1 kol2        kol3 kol4 kol5
1  10  a           11   20    20 
2  20  b           12   25    40 
3  30  c           13   30    60 
4  40  d           14   35    80 
5  50  e           15   40   100 
6 128  Meteorologi 16   45   256

### Mengatur penamaan kolom

In [204]:
colnames(df) # mengetahui nama kolom

[1] "kol1" "kol2" "kol3" "kol4" "kol5"

In [205]:
colnames(df) <- c('A', 'B', 'C', 'D', 'E') # penamaan ulang nama kolom
df

A   B           C  D  E  
1  10 a           11 20  20
2  20 b           12 25  40
3  30 c           13 30  60
4  40 d           14 35  80
5  50 e           15 40 100
6 128 Meteorologi 16 45 256

In [206]:
colnames(df)[1] <- 'X' # penamaan ulang kolom secara individual
df

X   B           C  D  E  
1  10 a           11 20  20
2  20 b           12 25  40
3  30 c           13 30  60
4  40 d           14 35  80
5  50 e           15 40 100
6 128 Meteorologi 16 45 256

In [207]:
colnames(df)[c(2,3)] <- c('Y','Z')
df

X   Y           Z  D  E  
1  10 a           11 20  20
2  20 b           12 25  40
3  30 c           13 30  60
4  40 d           14 35  80
5  50 e           15 40 100
6 128 Meteorologi 16 45 256

### Menyeleksi banyak baris dan kolom

In [208]:
df[1:3,]

X  Y Z  D  E 
1 10 a 11 20 20
2 20 b 12 25 40
3 30 c 13 30 60

In [209]:
# menyeleksi seluruh baris, kecuali no 3
df[-3,]

X   Y           Z  D  E  
1  10 a           11 20  20
2  20 b           12 25  40
4  40 d           14 35  80
5  50 e           15 40 100
6 128 Meteorologi 16 45 256

In [210]:
# penyeleksian kondisional
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [211]:
mtcars[mtcars$mpg > 20,]

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710     22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Merc 240D      24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona  21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Fiat X1-9      27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [212]:
mtcars[mtcars$mpg > 20 & mtcars$cyl == 6,]

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Hornet 4 Drive 21.4 6   258  110 3.08 3.215 19.44 1  0  3    1

In [213]:
mtcars[mtcars$mpg > 20 & mtcars$cyl == 6, c('mpg', 'cyl','hp')]

mpg  cyl hp 
Mazda RX4      21.0 6   110
Mazda RX4 Wag  21.0 6   110
Hornet 4 Drive 21.4 6   110

In [214]:
subset(mtcars, mpg > 20 & cyl == 6) # pakai built-in subset function

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Hornet 4 Drive 21.4 6   258  110 3.08 3.215 19.44 1  0  3    1

In [215]:
df[,1:3]

X   Y           Z 
1  10 a           11
2  20 b           12
3  30 c           13
4  40 d           14
5  50 e           15
6 128 Meteorologi 16

In [216]:
df[,c(3,5)]

Z  E  
1 11  20
2 12  40
3 13  60
4 14  80
5 15 100
6 16 256

In [217]:
df[,c('Z', 'E')]

Z  E  
1 11  20
2 12  40
3 13  60
4 14  80
5 15 100
6 16 256

### Menangani data kosong

In [218]:
df

X   Y           Z  D  E  
1  10 a           11 20  20
2  20 b           12 25  40
3  30 c           13 30  60
4  40 d           14 35  80
5  50 e           15 40 100
6 128 Meteorologi 16 45 256

In [219]:
is.na(df) # cek data kosong

X     Y     Z     D     E    
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE FALSE FALSE
[4,] FALSE FALSE FALSE FALSE FALSE
[5,] FALSE FALSE FALSE FALSE FALSE
[6,] FALSE FALSE FALSE FALSE FALSE

In [220]:
any(is.na(df))

[1] FALSE

In [221]:
any(is.na(df$X))

[1] FALSE

In [222]:
# Membuat na jadi 0
any(is.na(df)) <- 0.5 # error karena ga ada na

ERROR: Error in any(is.na(df)) <- 0.5: could not find function "any<-"


In [223]:
any(is.na(df$D)) <- mean(df$D)  # error karena ga ada na

ERROR: Error in any(is.na(df$D)) <- mean(df$D): could not find function "any<-"


# List

Kumpulan berbagai macam tipe data di R

In [224]:
v <- c(1,2,3,4,5)
M <- matrix(1:10, nrow=2)
c1 <- c('Ignatius', 'Laynez', 'Faber', 'Xaverius', 'Kanisius')
c2 <- c(42,37,28,45,43)

In [225]:
df <- data.frame(Nama = c1, ID = c2)
df

Nama     ID
1 Ignatius 42
2 Laynez   37
3 Faber    28
4 Xaverius 45
5 Kanisius 43

In [226]:
# Pendefinisian list
l <- list(v,M,df)
l

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

In [227]:
# penamaaan ulang indeks list

l2 <- list(sampel_vektor = v, sampel_matriks = M, sample_data_frame = df)
l2

$sampel_vektor
[1] 1 2 3 4 5

$sampel_matriks
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_data_frame
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

In [228]:
l2[1]

$sampel_vektor
[1] 1 2 3 4 5

In [229]:
l2['sampel_vektor']

$sampel_vektor
[1] 1 2 3 4 5

In [230]:
l2$sampel_vektor

[1] 1 2 3 4 5

In [231]:
l2[['sampel_vektor']]

[1] 1 2 3 4 5

In [232]:
print(class(l2['sampel_vektor']))
print(class(l2[1]))

[1] "list"
[1] "list"


In [233]:
print(class(l2$sampel_vektor))
print(class(l2[['sampel_vektor']]))

[1] "numeric"
[1] "numeric"


In [234]:
# Mengombinasikan dua list
l3 <- c(l,l2)
l3

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

$sampel_vektor
[1] 1 2 3 4 5

$sampel_matriks
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_data_frame
      Nama ID
1 Ignatius 42
2   Laynez 37
3    Faber 28
4 Xaverius 45
5 Kanisius 43

In [235]:
str(l2)

List of 3
 $ sampel_vektor    : num [1:5] 1 2 3 4 5
 $ sampel_matriks   : int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_data_frame:'data.frame':	5 obs. of  2 variables:
  ..$ Nama: Factor w/ 5 levels "Faber","Ignatius",..: 2 4 1 5 3
  ..$ ID  : num [1:5] 42 37 28 45 43


In [236]:
summary(l2)

                  Length Class      Mode   
sampel_vektor      5     -none-     numeric
sampel_matriks    10     -none-     numeric
sample_data_frame  2     data.frame list   

# Penanganan data tabular

## Penanganan data csv

In [237]:
getwd() # tahu di mana posisi kita saat ini

[1] "/home/ronggolawe/coding_repo/statdasWebinaR"

In [238]:
setwd("/home//ronggolawe/coding_repo/statdasWebinaR/") # mengatur posisi kita

In [239]:
getwd()

[1] "/home/ronggolawe/coding_repo/statdasWebinaR"

In [240]:
# Membaca csv
data <- read.csv("./data/gaji.csv")
data

ID NAMA       Gaji     Jurusan           
1 1  Petrus      1000000 Teologi           
2 2  Matius      2000000 Filsafat          
3 3  Markus      5000000 Meteorologi       
4 4  Barnabas   10000000 Teknik Informatika
5 5  Thomas     20000000 Sistem Informasi  
6 6  Ignatius     500000 Pendidikan Agama  
7 7  Aisyah     25000000 Teknik Elektro    
8 8  Supriyanto  1500000 Ilmu Perpustakaan

In [241]:
# menuliskan csv
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [242]:
write.csv(mtcars, file = "./data/tes.csv")

In [243]:
class(data)

[1] "data.frame"

In [244]:
# menuliskan csv dari data frame
c1 <- c(10,20,30,40,50)
c2 <- c('A', 'B', 'C', 'D', 'E')
df <- data.frame(c1,c2)
df

c1 c2
1 10 A 
2 20 B 
3 30 C 
4 40 D 
5 50 E

In [245]:
write.csv(df, file = './data/tes2.csv')

In [246]:
help(read.csv)

## Penanganan data excel

In [248]:
library(readxl) # memuat pustaka readxl

In [249]:
excel_sheets("./data/contoh.xlsx") 

[1] "Sheet1" "Sheet2"

In [250]:
# membaca file excel
df <- read_excel("./data/contoh.xlsx", sheet = "Sheet1")
df

No Nama Depan Nama Belakang Jenis Kelamin Negara          Usia ID  
1 1  Fernando   Sanchez       Pria          Meksiko         28   1562
2 2  Sandy      Herho         Pria          Indonesia       27   1582
3 3  Mara       Hashimoto     Wanita        Jepang          25   2587
4 4  Philip     Gent          Pria          Belgia          32   2468
5 5  Satya      Narendra      Pria          India           42   6548
6 6  Vincenza   Welland       Wanita        Amerika Serikat 40   3598
7 7  Rudy       Salim         Pria          Indonesia       65   7865
8 8  Gaston     Brumm         Pria          Amerika Serikat 24   2456
9 9  Etta       Hurn          Wanita        Britania Raya   34   1785

In [251]:
summary(df)

       No     Nama Depan        Nama Belakang      Jenis Kelamin     
 Min.   :1   Length:9           Length:9           Length:9          
 1st Qu.:3   Class :character   Class :character   Class :character  
 Median :5   Mode  :character   Mode  :character   Mode  :character  
 Mean   :5                                                           
 3rd Qu.:7                                                           
 Max.   :9                                                           
    Negara               Usia             ID      
 Length:9           Min.   :24.00   Min.   :1562  
 Class :character   1st Qu.:27.00   1st Qu.:1785  
 Mode  :character   Median :32.00   Median :2468  
                    Mean   :35.22   Mean   :3383  
                    3rd Qu.:40.00   3rd Qu.:3598  
                    Max.   :65.00   Max.   :7865  

In [252]:
str(df)

tibble [9 × 7] (S3: tbl_df/tbl/data.frame)
 $ No           : num [1:9] 1 2 3 4 5 6 7 8 9
 $ Nama Depan   : chr [1:9] "Fernando" "Sandy" "Mara" "Philip" ...
 $ Nama Belakang: chr [1:9] "Sanchez" "Herho" "Hashimoto" "Gent" ...
 $ Jenis Kelamin: chr [1:9] "Pria" "Pria" "Wanita" "Pria" ...
 $ Negara       : chr [1:9] "Meksiko" "Indonesia" "Jepang" "Belgia" ...
 $ Usia         : num [1:9] 28 27 25 32 42 40 65 24 34
 $ ID           : num [1:9] 1562 1582 2587 2468 6548 ...


In [253]:
mean(df$Usia)

[1] 35.22222

In [254]:
df1 <- read_excel("./data/contoh.xlsx", sheet='Sheet2')
df1

Bilangan Kuadrat
1 1         1     
2 2         4     
3 3         9     
4 4        16     
5 5        25

In [255]:
# menulis file excel
install.packages('writexl')
library(writexl)

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


In [256]:
c1 <- c(1:5)
c2 <- 6:10
df2 <- data.frame(c1,c2)
df2

c1 c2
1 1   6
2 2   7
3 3   8
4 4   9
5 5  10

In [257]:
write_xlsx(df2, "./data/tes.xlsx")

# Konsep - konsep inti pemrograman

## Operator - operator logika

### `&` (AND)

In [258]:
b <- 15
b

[1] 15

In [259]:
b < 20

[1] TRUE

In [260]:
b > 10

[1] TRUE

In [261]:
b > 10 & b < 20 # TRUE & TRUE = TRUE

[1] TRUE

In [262]:
b > 30 & b < 20 # FALSE & TRUE = FALSE

[1] FALSE

In [263]:
(b > 5) & (b < 25) & (b == 15) # TRUE & TRUE & TRUE = TRUE

[1] TRUE

In [264]:
(b < 5) & (b < 25) & (b == 15) # FALSE & TRUE & TRUE = FALSE

[1] FALSE

### `|` (OR)

In [265]:
(b==10) | (b < 25) # FALSE | TRUE = TRUE

[1] TRUE

In [266]:
(b > 10) | (b < 10)

[1] TRUE

In [267]:
(b > 10) | (b < 10) | (b == 12)

[1] TRUE

In [268]:
TRUE | FALSE

[1] TRUE

In [269]:
FALSE | FALSE

[1] FALSE

### `!` (NOT)

In [270]:
(b == 10) | (b < 25)

[1] TRUE

In [271]:
!((b == 10) | (b < 25))

[1] FALSE

In [272]:
!T

[1] FALSE

In [273]:
!(b > 10)

[1] FALSE

### Penerapan operator - operator logika pada data frame

In [274]:
# Kita juga dapat menggunakan operator - operator logika pada data frame
df <- mtcars

In [275]:
head(df)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [276]:
df[df$mpg > 20,'mpg']

[1] 21.0 21.0 22.8 21.4 24.4 22.8 32.4 30.4 33.9 21.5 27.3 26.0 30.4 21.4

In [277]:
subset(df, mpg > 20)

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710     22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Merc 240D      24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona  21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Fiat X1-9      27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [278]:
df[(df$mpg > 20) & (df$cyl > 4),]

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Hornet 4 Drive 21.4 6   258  110 3.08 3.215 19.44 1  0  3    1

In [279]:
df[(df$mpg > 20) | (df$cyl > 4),]

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3   
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3   
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3   
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4   
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4   
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4   
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2   
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2   
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4   
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2   
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4   
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6   
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8   
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

## Pernyataan `if`, `else`, dan `else if`

In [280]:
if (5 > 3){
    print('Bener, Bro!')
}

[1] "Bener, Bro!"


In [281]:
if (5 < 3){
    print('Bener, Bro!')
}

# tidak ada output karena kondisi FALSE

In [282]:
if (5 < 3){
    print('Bener, Bro!')
}else{
    print('Salah, Bro!')
}

[1] "Salah, Bro!"


In [283]:
a <- 10
b <- 20

if (a > b){
    print('a lebih besar dari b.')
}else{
    print('a lebih kecil dari b.')
}

[1] "a lebih kecil dari b."


In [284]:
minuman <- 'Coca Cola'

if (minuman == 'Kopi'){
    print('Ngopi, Bro!')
}else if (minuman == 'Coca Cola'){
    print('Mantap!')
}else if (minuman == 'air putih'){
    print('Bagus, Bro buat kesehatan.')
}else{
    print('Terserah mau minum apa, Bro yang penting halal.')
}

[1] "Mantap!"


## Pengulangan `while`

In [285]:
b <- 0
while (b < 10){
    print(b)
    b = b + 1
}

[1] 0
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9


In [286]:
b <- 0
while (b < 10){
    print(paste0('b sama dengan ',b))
    b = b + 1
}

[1] "b sama dengan 0"
[1] "b sama dengan 1"
[1] "b sama dengan 2"
[1] "b sama dengan 3"
[1] "b sama dengan 4"
[1] "b sama dengan 5"
[1] "b sama dengan 6"
[1] "b sama dengan 7"
[1] "b sama dengan 8"
[1] "b sama dengan 9"


In [287]:
b <- 0
while (b < 10){
    print(paste0('b sama dengan ',b))
    b = b + 1
    if (b == 10){
        print('b sama dengan 10. Pengulangan selesai.')
    }
}

[1] "b sama dengan 0"
[1] "b sama dengan 1"
[1] "b sama dengan 2"
[1] "b sama dengan 3"
[1] "b sama dengan 4"
[1] "b sama dengan 5"
[1] "b sama dengan 6"
[1] "b sama dengan 7"
[1] "b sama dengan 8"
[1] "b sama dengan 9"
[1] "b sama dengan 10. Pengulangan selesai."


In [288]:
b <- 0
while (b < 10){
    print(paste0('b sama dengan ',b))
    b = b + 1
    if (b == 10){
        print('b sama dengan 10. Pengulangan selesai.')
        print('Yuk Belajar pemrograman R!')
    }
}

[1] "b sama dengan 0"
[1] "b sama dengan 1"
[1] "b sama dengan 2"
[1] "b sama dengan 3"
[1] "b sama dengan 4"
[1] "b sama dengan 5"
[1] "b sama dengan 6"
[1] "b sama dengan 7"
[1] "b sama dengan 8"
[1] "b sama dengan 9"
[1] "b sama dengan 10. Pengulangan selesai."
[1] "Yuk Belajar pemrograman R!"


In [289]:
# penggunaan break() untuk mengakhiri pengulangan
b <- 0
while (b < 10){
    print(paste0('b sama dengan ',b))
    b = b + 1
    if (b == 10){
        print('b sama dengan 10. Pengulangan selesai.')
        break()
        print('Yuk Belajar pemrograman R!')
    }
}

[1] "b sama dengan 0"
[1] "b sama dengan 1"
[1] "b sama dengan 2"
[1] "b sama dengan 3"
[1] "b sama dengan 4"
[1] "b sama dengan 5"
[1] "b sama dengan 6"
[1] "b sama dengan 7"
[1] "b sama dengan 8"
[1] "b sama dengan 9"
[1] "b sama dengan 10. Pengulangan selesai."


In [290]:
b <- 0
while (b < 10){
    print(paste0('b sama dengan ',b))
    b = b + 1
    if (b == 5){
        print('b sama dengan 5. Pengulangan selesai.')
        break()
        print('Yuk Belajar pemrograman R!')
    }
}

[1] "b sama dengan 0"
[1] "b sama dengan 1"
[1] "b sama dengan 2"
[1] "b sama dengan 3"
[1] "b sama dengan 4"
[1] "b sama dengan 5. Pengulangan selesai."


## Pengulangan `for`

In [291]:
v <- c(1,2,3,4,5)

In [292]:
v

[1] 1 2 3 4 5

In [293]:
for (i in v){
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [294]:
for (i in v){
    print('Halo')
}

[1] "Halo"
[1] "Halo"
[1] "Halo"
[1] "Halo"
[1] "Halo"


In [295]:
buah2an <- c('Apel', 'Jeruk', 'Pisang', 'Mangga')

for (buah in buah2an){
    print(buah)
}

[1] "Apel"
[1] "Jeruk"
[1] "Pisang"
[1] "Mangga"


In [296]:
# Pengulangan for pada list
c1 <- c(10,20,30,40,50)
c2 <- c('A', 'B', 'C', 'D', 'E')
df <- data.frame(c1,c2)
df

c1 c2
1 10 A 
2 20 B 
3 30 C 
4 40 D 
5 50 E

In [297]:
v

[1] 1 2 3 4 5

In [298]:
l <- list(v,df)
l

[[1]]
[1] 1 2 3 4 5

[[2]]
  c1 c2
1 10  A
2 20  B
3 30  C
4 40  D
5 50  E

In [299]:
for (i in l){
    print(i)
}

[1] 1 2 3 4 5
  c1 c2
1 10  A
2 20  B
3 30  C
4 40  D
5 50  E


In [300]:
# Pengunaan pengulangan for pada matriks
mat <- matrix(1:25, nrow=5, byrow=T)
mat

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [301]:
for (num in mat){
    print(num)
}

[1] 1
[1] 6
[1] 11
[1] 16
[1] 21
[1] 2
[1] 7
[1] 12
[1] 17
[1] 22
[1] 3
[1] 8
[1] 13
[1] 18
[1] 23
[1] 4
[1] 9
[1] 14
[1] 19
[1] 24
[1] 5
[1] 10
[1] 15
[1] 20
[1] 25


In [302]:
# Pengulangan for bersarang
for (i in 1:5){
    print(i^2)
}

[1] 1
[1] 4
[1] 9
[1] 16
[1] 25


In [303]:
for (i in 1:5){
    for (j in 1:2){
        print(i*j)
    }
}

[1] 1
[1] 2
[1] 2
[1] 4
[1] 3
[1] 6
[1] 4
[1] 8
[1] 5
[1] 10



Proses kerjanya:
1. $1 \times 1$
2. $1 \times 2$
3. $2 \times 1$
4. $2 \times 2$
5. $3 \times 1$
6. $3 \times 2$, dst...

## Fungsi

In [304]:
# sintaks
nama_fungsi <- function(arg_1,arg_2, arg_3 = 10){
    # Kode yang hendak dieksekusi
    hasil <- arg_1 + arg_2
    return(hasil)
}

In [305]:
salam <- function(){
    print('Halo!')
}

In [306]:
salam()

[1] "Halo!"


In [307]:
salam <- function(nama){
    print(paste('Halo', nama, '!'))
}

In [308]:
salam('Sandy')

[1] "Halo Sandy !"


In [309]:
salam() # error karena tidak ada nama default

ERROR: Error in paste("Halo", nama, "!"): argument "nama" is missing, with no default


In [310]:
salam <- function(nama = 'Priska'){
    print(paste('Halo', nama, '!'))
}

In [311]:
salam()

[1] "Halo Priska !"


In [312]:
salam('Sandy')

[1] "Halo Sandy !"


In [313]:
penjumlahan <- function(b1,b2){
    print(b1 + b2)
}

In [314]:
penjumlahan(10,20)

[1] 30


In [315]:
# Harusnya pakai return 
penjumlahan <- function(b1,b2){
    return(b1 + b2)
}

In [316]:
x <- penjumlahan(10,20) # dapat disimpan di variabel
x

[1] 30

In [317]:
# Jangkauan variabel
kuadrat <- function(x){
    hasil <- x^2
    return(hasil)
}

In [318]:
out <- kuadrat(5)
out

[1] 25

In [319]:
hasil # ga ada karena bersifat lokal

ERROR: Error in eval(expr, envir, enclos): object 'hasil' not found


In [320]:
var <- 'Variabel global'
internet <- 'Jaringan global'

jaringan <- function(internet){
    print(var)
    internet <- 'Jaringan lokal'
    print(internet)
}

In [321]:
jaringan()
# redefinisi variabel lokal internet

[1] "Variabel global"
[1] "Jaringan lokal"


In [322]:
print(internet) # di luar fungsi berlaku variabel global

[1] "Jaringan global"


# Konsep - konsep pemrograman lanjut

## Fitur - fitur *built-in*

### `seq()`: Membuat sikuen

In [323]:
seq(0,10, by=2)

[1]  0  2  4  6  8 10

In [324]:
seq(0,100, by = 10)

[1]   0  10  20  30  40  50  60  70  80  90 100

In [325]:
seq(0,30, by = 2)

[1]  0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30

### `sort()` : Mengurutkan vektor

In [326]:
v <- c(2,7,1,49,54,32)
v

[1]  2  7  1 49 54 32

In [327]:
sort(v) # dari kecil ke besar

[1]  1  2  7 32 49 54

In [328]:
sort(v, decreasing = T) # dari besar ke kecil

[1] 54 49 32  7  2  1

In [329]:
nama <- c('s', 'a', 'n', 'd', 'y')
nama

[1] "s" "a" "n" "d" "y"

In [330]:
sort(nama)

[1] "a" "d" "n" "s" "y"

In [331]:
nama <- c('s', 'a', 'n', 'd', 'Y')
sort(nama)

[1] "a" "d" "n" "s" "Y"

In [332]:
nama <- c('s', 'a', 'n', 'd', 'Y','A')
sort(nama)

[1] "a" "A" "d" "n" "s" "Y"

### `rev()`: Membalikan elemen di dalam suatu objek

In [333]:
b <- seq(1,10)
b

[1]  1  2  3  4  5  6  7  8  9 10

In [334]:
rev(b)

[1] 10  9  8  7  6  5  4  3  2  1

In [335]:
d <- c('a','b','e','d')
d

[1] "a" "b" "e" "d"

In [336]:
rev(d)

[1] "d" "e" "b" "a"

### `str()`: Menunjukkan struktur dari suatu objek


In [337]:
str(b)

 int [1:10] 1 2 3 4 5 6 7 8 9 10


In [338]:
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


In [339]:
summary(mtcars)

      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb      
 Min.   :0.0000   Min.   :3.000  

### `append()`: Menggabungkan objek

In [340]:
v1 <- seq(1,5)
v2 <- seq(10,30, by=10)

In [341]:
append(v1,v2)

[1]  1  2  3  4  5 10 20 30

### Memeriksa dan mengonversi tipe data pada objek - objek R

In [342]:
v1

[1] 1 2 3 4 5

In [343]:
is.vector(v1)

[1] TRUE

In [344]:
is.data.frame(v1)

[1] FALSE

In [345]:
is.data.frame(mtcars)

[1] TRUE

In [346]:
as.list(v1)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

In [347]:
as.matrix(v1)

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5

## Fungsi - fungsi `apply`

In [348]:
v <- seq(10,50,by=10)
v

[1] 10 20 30 40 50

In [349]:
sample(v,2) # mengambil dua buah sampel acak dari vektor

[1] 30 50

In [350]:
sample(1:100,5)

[1] 41 73 64 63 75

In [351]:
v <- 1:5
v

[1] 1 2 3 4 5

In [352]:
tambah_acak <- function(x){
    acak <- sample(1:100,1)
    return(x + acak)
}

In [353]:
tambah_acak(10)

[1] 15

In [354]:
hasil <- tambah_acak(20)
hasil

[1] 21

### `lapply()`: dalam bentuk list

In [355]:
lapply(v, tambah_acak)
# outputnya dalam bentuk list

[[1]]
[1] 11

[[2]]
[1] 77

[[3]]
[1] 86

[[4]]
[1] 81

[[5]]
[1] 39

## `sapply()`: dalam bentuk vektor

In [356]:
sapply(v,tambah_acak)

[1]  17   5 103   6  63

In [357]:
v1 <- seq(5,25, by=5)
kuadrat <- function(bil){
    return(bil^2)
}

In [358]:
kuadrat(5)

[1] 25

In [359]:
lapply(v, kuadrat)

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9

[[4]]
[1] 16

[[5]]
[1] 25

In [360]:
sapply(v, kuadrat)

[1]  1  4  9 16 25

### Fungsi anonim

In [361]:
v

[1] 1 2 3 4 5

In [362]:
kuadrat <- function(bil){
    return(bil^2)
}

In [363]:
sapply(v, function(bil){bil^2}) # fungsi anonim

[1]  1  4  9 16 25

### Fungsi `apply` dengan banyak *input*

In [364]:
v

[1] 1 2 3 4 5

In [365]:
tambah_dua_bil <- function(b1,b2){
    return(b1+b2)
}

In [366]:
tambah_dua_bil(20,30)

[1] 50

In [367]:
sapply(v, tambah_dua_bil) # error

ERROR: Error in FUN(X[[i]], ...): argument "b2" is missing, with no default


In [368]:
sapply(v, tambah_dua_bil, b2 = 10)

[1] 11 12 13 14 15

## Ekspresi regular : RegEx

In [369]:
txt <- "Halo semuanya! Selamat Pagi! Cuaca lagi bagus, nih buat touring."

In [370]:
txt

[1] "Halo semuanya! Selamat Pagi! Cuaca lagi bagus, nih buat touring."

In [371]:
grepl("Halo",txt) # kata "Halo" ada di txt

[1] TRUE

In [372]:
grepl("Malam", txt)

[1] FALSE

In [373]:
grepl("halo", txt) # Sifatnya case-sensitive

[1] FALSE

In [374]:
v <- c('a','d','k', 'l','t','k')
grepl('k',v)

[1] FALSE FALSE  TRUE FALSE FALSE  TRUE

In [375]:
grep('k',v) # outputnya indeks

[1] 3 6

In [376]:
grep('a',v)

[1] 1

## Fungsi - fungsi matematika

### `abs()`: menghitung nilai absolut

In [377]:
abs(-2)

[1] 2

In [378]:
v <- c(-3,-5,7,10)
abs(v)

[1]  3  5  7 10

### `sum()`: menghitung penjumlahan seluruh elemen

In [379]:
sum(2,4,6)

[1] 12

In [380]:
v <- c(2,3,4,5)
sum(v)

[1] 14

### `mean()`: menghitung rata - rata aritmatika   

In [381]:
mean(v)

[1] 3.5

In [382]:
mean(3,4)

[1] 3

### `round()`: membulatkan nilai

In [383]:
round(2.777645)

[1] 3

In [384]:
round(2.777645, digits=2)

[1] 2.78

In [385]:
round(2.777645, 4)

[1] 2.7776

## *Dates* dan *Timestemps*

In [386]:
Sys.Date() # waktu saat ini

[1] "2020-06-30"

In [387]:
d <- Sys.Date()
d

[1] "2020-06-30"

In [388]:
class(d)

[1] "Date"

In [389]:
d <- '1993-03-13'
d

[1] "1993-03-13"

In [390]:
class(d)

[1] "character"

In [391]:
# dikonversi menjadi date
b.day <- as.Date(d)
b.day

[1] "1993-03-13"

In [392]:
class(b.day)

[1] "Date"

In [393]:
as.Date('Mar-13-93') # format tidak sesuai

ERROR: Error in charToDate(x): character string is not in a standard unambiguous format


In [394]:
as.Date('Mar-13-93', format = '%b-%d-%y')

[1] "1993-03-13"

* `%d`: hari (desimal)
* `%m`: bulan (desimal)
* `%b`: bulan (singkatan)
* `%B`: bulan (tidak disingkat)
* `%y`: tahun (2 digit)
* `%Y`: tahun (4 digit)

In [395]:
as.Date('March,01,2009', format= "%B, %d, %Y")

[1] "2009-03-01"

In [396]:
# POSIXct

In [397]:
as.POSIXct('11:03:05', format='%H:%M:%S')

[1] "2020-06-30 11:03:05 WIB"

In [398]:
strptime('11:03:05', format = '%H:%M:%S') # lebih banyak dipakai di pemrograman R

[1] "2020-06-30 11:03:05 WIB"

# Manipulasi data

## dplyr

In [399]:
install.packages("dplyr")
install.packages("nycflights13")

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


In [400]:
library(dplyr)
library(nycflights13)


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



In [401]:
head(flights)

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819          
2 2013 1     1   533      529             4         850      830          
3 2013 1     1   542      540             2         923      850          
4 2013 1     1   544      545            -1        1004     1022          
5 2013 1     1   554      600            -6         812      837          
6 2013 1     1   554      558            -4         740      728          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15    
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29    
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40    
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45    
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0    
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58    
  time_hour          
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

### `filter()`

In [402]:
head(filter(flights,month == 5, day == 2, carrier == 'AA'))

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 5     2   539      540             -1       850      840           
2 2013 5     2   549      600            -11       823      850           
3 2013 5     2   558      605             -7       855      910           
4 2013 5     2   603      610             -7       729      745           
5 2013 5     2   611      615             -4       900      915           
6 2013 5     2   627      630             -3       736      805           
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  10       AA       701   N5DYAA  JFK    MIA  149      1089     5    40    
2 -27       AA       707   N3ANAA  LGA    DFW  191      1389     6     0    
3 -15       AA      1837   N3FRAA  LGA    MIA  149      1096     6     5    
4 -16       AA       301   N4YJAA  LGA    ORD  109       733     6    10    
5 -15       AA      1895   N3HEAA  EWR    MIA  146      1085     6    15    
6 -29       AA       303   N200AA  LGA    ORD  112       733     6    30    
  time_hour          
1 2013-05-02 05:00:00
2 2013-05-02 06:00:00
3 2013-05-02 06:00:00
4 2013-05-02 06:00:00
5 2013-05-02 06:00:00
6 2013-05-02 06:00:00

In [403]:
head(flights[flights$month == 5 & flights$day == 2 & flights$carrier == 'AA',]) # ribet

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 5     2   539      540             -1       850      840           
2 2013 5     2   549      600            -11       823      850           
3 2013 5     2   558      605             -7       855      910           
4 2013 5     2   603      610             -7       729      745           
5 2013 5     2   611      615             -4       900      915           
6 2013 5     2   627      630             -3       736      805           
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  10       AA       701   N5DYAA  JFK    MIA  149      1089     5    40    
2 -27       AA       707   N3ANAA  LGA    DFW  191      1389     6     0    
3 -15       AA      1837   N3FRAA  LGA    MIA  149      1096     6     5    
4 -16       AA       301   N4YJAA  LGA    ORD  109       733     6    10    
5 -15       AA      1895   N3HEAA  EWR    MIA  146      1085     6    15    
6 -29       AA       303   N200AA  LGA    ORD  112       733     6    30    
  time_hour          
1 2013-05-02 05:00:00
2 2013-05-02 06:00:00
3 2013-05-02 06:00:00
4 2013-05-02 06:00:00
5 2013-05-02 06:00:00
6 2013-05-02 06:00:00

### `slice()`

In [404]:
slice(flights, 1:10) # menyeleksi 10 baris pertama

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1  2013 1     1   517      515             2         830      819          
2  2013 1     1   533      529             4         850      830          
3  2013 1     1   542      540             2         923      850          
4  2013 1     1   544      545            -1        1004     1022          
5  2013 1     1   554      600            -6         812      837          
6  2013 1     1   554      558            -4         740      728          
7  2013 1     1   555      600            -5         913      854          
8  2013 1     1   557      600            -3         709      723          
9  2013 1     1   557      600            -3         838      846          
10 2013 1     1   558      600            -2         753      745          
   arr_delay carrier flight tailnum origin dest air_time distance hour minute
1   11       UA      1545   N14228  EWR    IAH  227      1400     5    15    
2   20       UA      1714   N24211  LGA    IAH  227      1416     5    29    
3   33       AA      1141   N619AA  JFK    MIA  160      1089     5    40    
4  -18       B6       725   N804JB  JFK    BQN  183      1576     5    45    
5  -25       DL       461   N668DN  LGA    ATL  116       762     6     0    
6   12       UA      1696   N39463  EWR    ORD  150       719     5    58    
7   19       B6       507   N516JB  EWR    FLL  158      1065     6     0    
8  -14       EV      5708   N829AS  LGA    IAD   53       229     6     0    
9   -8       B6        79   N593JB  JFK    MCO  140       944     6     0    
10   8       AA       301   N3ALAA  LGA    ORD  138       733     6     0    
   time_hour          
1  2013-01-01 05:00:00
2  2013-01-01 05:00:00
3  2013-01-01 05:00:00
4  2013-01-01 05:00:00
5  2013-01-01 06:00:00
6  2013-01-01 05:00:00
7  2013-01-01 06:00:00
8  2013-01-01 06:00:00
9  2013-01-01 06:00:00
10 2013-01-01 06:00:00

### `arrange()`

In [405]:
head(arrange(flights, year, month, day, arr_time))
# mengatur urutan sesuai kolomnya

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   1929     1920             9        3          7          
2 2013 1     1   2121     2040            41        6       2323          
3 2013 1     1   2058     2100            -2        8       2359          
4 2013 1     1   2120     2130           -10       16         18          
5 2013 1     1   2134     2045            49       20       2352          
6 2013 1     1   2312     2000           192       21       2110          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  -4       UA      1071   N27205  EWR    BQN  192      1585     19   20    
2  43       B6       227   N307JB  EWR    MCO  143       937     20   40    
3   9       UA      1241   N27724  EWR    TPA  159       997     21    0    
4  -2       B6       383   N603JB  LGA    FLL  160      1076     21   30    
5  28       UA      1106   N27733  EWR    FLL  152      1065     20   45    
6 191       EV      4312   N13958  EWR    DCA   44       199     20    0    
  time_hour          
1 2013-01-01 19:00:00
2 2013-01-01 20:00:00
3 2013-01-01 21:00:00
4 2013-01-01 21:00:00
5 2013-01-01 20:00:00
6 2013-01-01 20:00:00

### `select()`

In [407]:
head(select(flights, arr_time)) # seleksi kolom arr_time

arr_time
1  830    
2  850    
3  923    
4 1004    
5  812    
6  740

In [408]:
head(select(flights,carrier)) # seleksi kolom carrier

carrier
1 UA     
2 UA     
3 AA     
4 B6     
5 DL     
6 UA

In [409]:
head(select(flights, arr_time, carrier, month)) # seleksi 3 kolom

arr_time carrier month
1  830     UA      1    
2  850     UA      1    
3  923     AA      1    
4 1004     B6      1    
5  812     DL      1    
6  740     UA      1

### `rename()`:

In [410]:
head(flights)

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819          
2 2013 1     1   533      529             4         850      830          
3 2013 1     1   542      540             2         923      850          
4 2013 1     1   544      545            -1        1004     1022          
5 2013 1     1   554      600            -6         812      837          
6 2013 1     1   554      558            -4         740      728          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15    
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29    
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40    
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45    
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0    
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58    
  time_hour          
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

In [411]:
rename(flights,new_arr_time = arr_time) # mengubah nama kolom

year month day dep_time sched_dep_time dep_delay new_arr_time
1      2013 1     1   517      515             2         830        
2      2013 1     1   533      529             4         850        
3      2013 1     1   542      540             2         923        
4      2013 1     1   544      545            -1        1004        
5      2013 1     1   554      600            -6         812        
6      2013 1     1   554      558            -4         740        
7      2013 1     1   555      600            -5         913        
8      2013 1     1   557      600            -3         709        
9      2013 1     1   557      600            -3         838        
10     2013 1     1   558      600            -2         753        
11     2013 1     1   558      600            -2         849        
12     2013 1     1   558      600            -2         853        
13     2013 1     1   558      600            -2         924        
14     2013 1     1   558      600            -2         923        
15     2013 1     1   559      600            -1         941        
16     2013 1     1   559      559             0         702        
17     2013 1     1   559      600            -1         854        
18     2013 1     1   600      600             0         851        
19     2013 1     1   600      600             0         837        
20     2013 1     1   601      600             1         844        
21     2013 1     1   602      610            -8         812        
22     2013 1     1   602      605            -3         821        
23     2013 1     1   606      610            -4         858        
24     2013 1     1   606      610            -4         837        
25     2013 1     1   607      607             0         858        
26     2013 1     1   608      600             8         807        
27     2013 1     1   611      600            11         945        
28     2013 1     1   613      610             3         925        
29     2013 1     1   615      615             0        1039        
30     2013 1     1   615      615             0         833        
...    ...  ...   ... ...      ...            ...       ...         
336747 2013 9     30  2123     2125            -2       2223        
336748 2013 9     30  2127     2129            -2       2314        
336749 2013 9     30  2128     2130            -2       2328        
336750 2013 9     30  2129     2059            30       2230        
336751 2013 9     30  2131     2140            -9       2225        
336752 2013 9     30  2140     2140             0         10        
336753 2013 9     30  2142     2129            13       2250        
336754 2013 9     30  2145     2145             0        115        
336755 2013 9     30  2147     2137            10         30        
336756 2013 9     30  2149     2156            -7       2245        
336757 2013 9     30  2150     2159            -9       2250        
336758 2013 9     30  2159     1845           194       2344        
336759 2013 9     30  2203     2205            -2       2339        
336760 2013 9     30  2207     2140            27       2257        
336761 2013 9     30  2211     2059            72       2339        
336762 2013 9     30  2231     2245           -14       2335        
336763 2013 9     30  2233     2113            80        112        
336764 2013 9     30  2235     2001           154         59        
336765 2013 9     30  2237     2245            -8       2345        
336766 2013 9     30  2240     2245            -5       2334        
336767 2013 9     30  2240     2250           -10       2347        
336768 2013 9     30  2241     2246            -5       2345        
336769 2013 9     30  2307     2255            12       2359        
336770 2013 9     30  2349     2359           -10        325        
336771 2013 9     30    NA     1842            NA         NA        
336772 2013 9     30    NA     1455            NA         NA        
33677

### `distinct()`

Untuk menyeleksi nilai - nilai unik

In [412]:
distinct(select(flights, carrier)) # nilai - nilai unik pada kolom carrier

carrier
1  UA     
2  AA     
3  B6     
4  DL     
5  EV     
6  MQ     
7  US     
8  WN     
9  VX     
10 FL     
11 AS     
12 9E     
13 F9     
14 HA     
15 YV     
16 OO

In [413]:
distinct(select(flights,month))

month
1   1   
2  10   
3  11   
4  12   
5   2   
6   3   
7   4   
8   5   
9   6   
10  7   
11  8   
12  9

### `mutate()`

Menambahkan kolom baru di data frame

In [418]:
mutate(flights, kol_baru = arr_delay - dep_delay)

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1     1   517      515             2         830      819          
2      2013 1     1   533      529             4         850      830          
3      2013 1     1   542      540             2         923      850          
4      2013 1     1   544      545            -1        1004     1022          
5      2013 1     1   554      600            -6         812      837          
6      2013 1     1   554      558            -4         740      728          
7      2013 1     1   555      600            -5         913      854          
8      2013 1     1   557      600            -3         709      723          
9      2013 1     1   557      600            -3         838      846          
10     2013 1     1   558      600            -2         753      745          
11     2013 1     1   558      600            -2         849      851          
12     2013 1     1   558      600            -2         853      856          
13     2013 1     1   558      600            -2         924      917          
14     2013 1     1   558      600            -2         923      937          
15     2013 1     1   559      600            -1         941      910          
16     2013 1     1   559      559             0         702      706          
17     2013 1     1   559      600            -1         854      902          
18     2013 1     1   600      600             0         851      858          
19     2013 1     1   600      600             0         837      825          
20     2013 1     1   601      600             1         844      850          
21     2013 1     1   602      610            -8         812      820          
22     2013 1     1   602      605            -3         821      805          
23     2013 1     1   606      610            -4         858      910          
24     2013 1     1   606      610            -4         837      845          
25     2013 1     1   607      607             0         858      915          
26     2013 1     1   608      600             8         807      735          
27     2013 1     1   611      600            11         945      931          
28     2013 1     1   613      610             3         925      921          
29     2013 1     1   615      615             0        1039     1100          
30     2013 1     1   615      615             0         833      842          
...    ...  ...   ... ...      ...            ...       ...      ...           
336747 2013 9     30  2123     2125            -2       2223     2247          
336748 2013 9     30  2127     2129            -2       2314     2323          
336749 2013 9     30  2128     2130            -2       2328     2359          
336750 2013 9     30  2129     2059            30       2230     2232          
336751 2013 9     30  2131     2140            -9       2225     2255          
336752 2013 9     30  2140     2140             0         10       40          
336753 2013 9     30  2142     2129            13       2250     2239          
336754 2013 9     30  2145     2145             0        115      140          
336755 2013 9     30  2147     2137            10         30       27          
336756 2013 9     30  2149     2156            -7       2245     2308          
336757 2013 9     30  2150     2159            -9       2250     2306          
336758 2013 9     30  2159     1845           194       2344     2030          
336759 2013 9     30  2203     2205            -2       2339     2331          
336760 2013 9     30  2207     2140            27       2257     2250          
336761 2013 9     30  2211     2059            72       2339     2242          
336762 2013 9     30  2231     2245           -14       2335     2356          
336763 2013 9     30  2233     2113            80        112       30          
336764 2013 9     30  2235     2001           154         59     2249          
336765 

### `transmute()`

Sama seperti `mutate()`, namu hanya mengeluarkan *output* kolom baru yang dihasilkan.

In [419]:
transmute(flights, kol_baru = arr_delay - dep_delay)

kol_baru
1        9     
2       16     
3       31     
4      -17     
5      -19     
6       16     
7       24     
8      -11     
9       -5     
10      10     
11       0     
12      -1     
13       9     
14     -12     
15      32     
16      -4     
17      -7     
18      -7     
19      12     
20      -7     
21       0     
22      19     
23      -8     
24      -4     
25     -17     
26      24     
27       3     
28       1     
29     -21     
30      -9     
...    ...     
336747 -22     
336748  -7     
336749 -29     
336750 -32     
336751 -21     
336752 -30     
336753  -2     
336754 -25     
336755  -7     
336756 -16     
336757  -7     
336758   0     
336759  10     
336760 -20     
336761 -15     
336762  -7     
336763 -38     
336764 -24     
336765   0     
336766 -12     
336767 -10     
336768 -11     
336769 -11     
336770 -15     
336771  NA     
336772  NA     
336773  NA     
336774  NA     
336775  NA     
336776  NA

### `summarise()`

In [420]:
summarise(flights, rata2wktTerbang = mean(air_time, na.rm = T)) 
# sama seperti fungsi agregate di R

rata2wktTerbang
1 150.6865

In [421]:
summarise(flights, JmlhwktTerbang = sum(air_time, na.rm = T)) 

JmlhwktTerbang
1 49326610

### `sample_n()` dan `sample_frac()`

In [424]:
sample_n(flights, 3) # mensampel 3 baris acak

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013  4    22  2250     2105           105         56     2305          
2 2013  2    13  2156     2135            21       2328     2300          
3 2013 10     8   554      600            -6        731      758          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 111       MQ      4573   N725MQ  LGA    DTW  85       502      21    5    
2  28       B6       104   N348JB  JFK    BUF  60       301      21   35    
3 -27       EV      5068   N131EV  EWR    DTW  76       488       6    0    
  time_hour          
1 2013-04-22 21:00:00
2 2013-02-13 21:00:00
3 2013-10-08 06:00:00

In [427]:
sample_frac(flights, 0.01) # mensampel 1 % dari seluruh baris

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1    2013 11    13   858      903            -5       1217     1237          
2    2013 12    17  1030     1034            -4       1328     1319          
3    2013  5    25   553      600            -7        832      854          
4    2013 11    16  1859     1900            -1       2227     2246          
5    2013  2     5  1438     1440            -2       1535     1549          
6    2013  7    11   611      605             6        732      720          
7    2013 11    11  2045     2045             0       2346     2359          
8    2013  4    23   648      650            -2        954     1006          
9    2013  8    13  2228     2231            -3        218      226          
10   2013  3    15  1541     1545            -4       1925     1921          
11   2013  5    21   758      806            -8        945     1003          
12   2013  3    28  2036     2040            -4       2330     2356          
13   2013 12    19  1745     1710            35       1949     1910          
14   2013  3     5  1227     1210            17       1324     1315          
15   2013  6    13   552      600            -8        658      712          
16   2013  9    13  1926     1930            -4       2147     2125          
17   2013  6    22  1659     1700            -1       1923     2000          
18   2013 11    10  1003     1010            -7       1209     1243          
19   2013 10    16   552      600            -8        655      659          
20   2013  7     8   643      649            -6        747      810          
21   2013  9    13  2058     2017            41       2225     2159          
22   2013 10    24  2100     2059             1       2342     2358          
23   2013  2     1  1020     1015             5       1128     1131          
24   2013 10    28  1851     1855            -4       2033     2035          
25   2013  3    25  1458     1459            -1       1753     1825          
26   2013  4    27   908      912            -4       1150     1200          
27   2013  8    22  1842     1712            90       1950     1844          
28   2013  2    17   635      610            25        924      910          
29   2013  8    27   721      725            -4        809      822          
30   2013  7    26   746      800           -14        949     1005          
...  ...  ...   ... ...      ...            ...       ...      ...           
3339 2013  8     1  1551     1545             6       1942     2005          
3340 2013  2    25  1254     1300            -6       1539     1537          
3341 2013  1    21  1750     1645            65       2044     2005          
3342 2013 11    30  1255     1300            -5       1527     1538          
3343 2013 11    17  1604     1555             9       1808     1755          
3344 2013 11    25   952     1000            -8       1127     1135          
3345 2013  5     2  1544     1500            44       1749     1722          
3346 2013  9     9  1932     1900            32       2045     2018          
3347 2013 10     4  1717     1555            82       1851     1740          
3348 2013  5    18  1617     1540            37       1741     1733          
3349 2013  5    14  1825     1830            -5       2116     2200          
3350 2013  8    23    NA     1940            NA         NA     2059          
3351 2013 10     5   830      835            -5       1009     1030          
3352 2013  2    22  1847     1850            -3       2153     2229          
3353 2013  7    18   703      710            -7        858      915          
3354 2013  5    22  1633     1455            98       1759     1638          
3355 2013  7     2  1906     1855            11       2158     2205          
3356 2013  7    28   931      940            -9       1028     1051          
3357 2013  4    21  1154     1200            -6       1248     1305          
3358 2013 10    14  1005   

## Operator *pipe*

In [428]:
df <- mtcars

In [429]:
head(df)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

### *Nesting*

In [430]:
filter(df, mpg > 20)

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4      21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag  21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710     22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Merc 240D      24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona  21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Fiat X1-9      27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [431]:
sample_n(filter(df, mpg > 20), size = 5) # dua operasi secara bersamaan

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2   
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Merc 230       22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2

In [435]:
hasil <- arrange(sample_n(filter(df, mpg > 20), size = 5), desc(mpg))
# memfilter df untuk mpg > 20
# mengambil 5 baris sampel acak
# mengurutkannya berdasarkan kolom mpg secara terbalik (descending order)
hasil

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Fiat 128    32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic 30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Fiat X1-9   27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Merc 230    22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Volvo 142E  21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [436]:
# susah dibaca!!!

### Penugasan berganda

In [438]:
a <- filter(df, mpg > 20)
b <- sample_n(a, size = 5)
hasil <- arrange(b, desc(mpg))
hasil

mpg  cyl disp  hp drat wt    qsec  vs am gear carb
Fiat 128      32.4 4    78.7 66 4.08 2.200 19.47 1  1  4    1   
Honda Civic   30.4 4    75.7 52 4.93 1.615 18.52 1  1  4    2   
Fiat X1-9     27.3 4    79.0 66 4.08 1.935 18.90 1  1  4    1   
Datsun 710    22.8 4   108.0 93 3.85 2.320 18.61 1  1  4    1   
Toyota Corona 21.5 4   120.1 97 3.70 2.465 20.01 1  0  3    1

### Operator *pipe*

In [441]:
hasil <- df %>% filter(mpg > 20) %>% sample_n(size = 5) %>% arrange(desc(mpg))
# lebih mudah diBACA!
hasil

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Toyota Corolla 33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Fiat 128       32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic    30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Merc 240D      24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Hornet 4 Drive 21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1

## tidyr

 * dplyr $\rightarrow$ manipulasi data.
 * tidyr $\rightarrow$ pembersihan data.

In [443]:
install.packages("tidyr")
install.packages("data.table") # punya kelebihan soal waktu eksekusi dibandingkan data frame

Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done


In [444]:
library(tidyr)
library(data.table)


Attaching package: ‘data.table’

The following objects are masked from ‘package:dplyr’:

    between, first, last



### `gather()`

Membagi kolom menjadi pasangan *key*-*value*

In [447]:
v <- c('A', 'B', 'C','A', 'B', 'C','A', 'B', 'C')
thn <- c(2020,2021,2022,2020,2021,2022,2020,2021,2022)

q1 <- runif(n = 9, min = 0, max = 100)
q2 <- runif(n = 9, min = 0, max = 100)
q3 <- runif(n = 9, min = 0, max = 100)
q4 <- runif(n = 9, min = 0, max = 100)

df <- data.frame(Perusahaan = v, Tahun = thn, q1, q2, q3, q4)
df

Perusahaan Tahun q1        q2        q3       q4         
1 A          2020  38.894418  1.654605 40.71380 15.88689983
2 B          2021  89.734563 60.179006 82.11529 55.55778290
3 C          2022  52.087442 39.370503 55.70252 65.97746897
4 A          2020  93.594023 12.396570 91.24406  5.59198416
5 B          2021  87.816012 82.021958 86.38469  0.07934286
6 C          2022   1.486082 73.739042 76.69074 85.98627327
7 A          2020  78.902340 69.518334 52.49779 72.99245074
8 B          2021  22.836693 94.801048 13.75364 42.27830907
9 C          2022  68.204620 24.498203 66.46980 24.85925895

In [448]:
gather(data = df, key = 'Kuarter', value = 'Keuntungan', q1:q4)
# 4 kolom dibuat jadi 2 kolom

Perusahaan Tahun Kuarter Keuntungan 
1  A          2020  q1      38.89441818
2  B          2021  q1      89.73456286
3  C          2022  q1      52.08744234
4  A          2020  q1      93.59402261
5  B          2021  q1      87.81601237
6  C          2022  q1       1.48608228
7  A          2020  q1      78.90234042
8  B          2021  q1      22.83669275
9  C          2022  q1      68.20461997
10 A          2020  q2       1.65460471
11 B          2021  q2      60.17900605
12 C          2022  q2      39.37050325
13 A          2020  q2      12.39656997
14 B          2021  q2      82.02195833
15 C          2022  q2      73.73904230
16 A          2020  q2      69.51833363
17 B          2021  q2      94.80104796
18 C          2022  q2      24.49820316
19 A          2020  q3      40.71380387
20 B          2021  q3      82.11529187
21 C          2022  q3      55.70251632
22 A          2020  q3      91.24406322
23 B          2021  q3      86.38468848
24 C          2022  q3      76.69073627
25 A          2020  q3      52.49778645
26 B          2021  q3      13.75364345
27 C          2022  q3      66.46980187
28 A          2020  q4      15.88689983
29 B          2021  q4      55.55778290
30 C          2022  q4      65.97746897
31 A          2020  q4       5.59198416
32 B          2021  q4       0.07934286
33 C          2022  q4      85.98627327
34 A          2020  q4      72.99245074
35 B          2021  q4      42.27830907
36 C          2022  q4      24.85925895

In [449]:
# menggunakan fungsi gather() dengan menggunakan operator pipe

df %>% gather(key = 'Kuarter', value = 'Keuntungan', q1:q4)

Perusahaan Tahun Kuarter Keuntungan 
1  A          2020  q1      38.89441818
2  B          2021  q1      89.73456286
3  C          2022  q1      52.08744234
4  A          2020  q1      93.59402261
5  B          2021  q1      87.81601237
6  C          2022  q1       1.48608228
7  A          2020  q1      78.90234042
8  B          2021  q1      22.83669275
9  C          2022  q1      68.20461997
10 A          2020  q2       1.65460471
11 B          2021  q2      60.17900605
12 C          2022  q2      39.37050325
13 A          2020  q2      12.39656997
14 B          2021  q2      82.02195833
15 C          2022  q2      73.73904230
16 A          2020  q2      69.51833363
17 B          2021  q2      94.80104796
18 C          2022  q2      24.49820316
19 A          2020  q3      40.71380387
20 B          2021  q3      82.11529187
21 C          2022  q3      55.70251632
22 A          2020  q3      91.24406322
23 B          2021  q3      86.38468848
24 C          2022  q3      76.69073627
25 A          2020  q3      52.49778645
26 B          2021  q3      13.75364345
27 C          2022  q3      66.46980187
28 A          2020  q4      15.88689983
29 B          2021  q4      55.55778290
30 C          2022  q4      65.97746897
31 A          2020  q4       5.59198416
32 B          2021  q4       0.07934286
33 C          2022  q4      85.98627327
34 A          2020  q4      72.99245074
35 B          2021  q4      42.27830907
36 C          2022  q4      24.85925895

### `spread()`

In [453]:
saham <- data.frame(
    waktu = as.Date('2009-01-01') + 0:9,
    X = rnorm(10,0,1),
    Y = rnorm(10,0,2),
    Z = rnorm(10,0,4)
)

In [454]:
saham

waktu      X           Y          Z         
1  2009-01-01 -0.73932297 -2.1693354  2.7072974
2  2009-01-02 -0.66060205  0.5871750  3.3650593
3  2009-01-03  0.52308703 -1.4795559  0.5510204
4  2009-01-04  1.03084445 -0.4394464 -0.1908767
5  2009-01-05  0.05471038  2.2671503  5.0201738
6  2009-01-06 -1.02139422  1.6965900  6.7124031
7  2009-01-07  0.62023365  0.8673688  1.4242770
8  2009-01-08  0.75474458 -0.8452750  4.0341163
9  2009-01-09 -1.18884672 -1.8846370  2.7653468
10 2009-01-10 -1.03766147  3.1065358 -1.0139824

In [457]:
saham.gather <- gather(saham, key = saham, value = harga, X,Y,Z)
saham.gather

waktu      saham harga      
1  2009-01-01 X     -0.73932297
2  2009-01-02 X     -0.66060205
3  2009-01-03 X      0.52308703
4  2009-01-04 X      1.03084445
5  2009-01-05 X      0.05471038
6  2009-01-06 X     -1.02139422
7  2009-01-07 X      0.62023365
8  2009-01-08 X      0.75474458
9  2009-01-09 X     -1.18884672
10 2009-01-10 X     -1.03766147
11 2009-01-01 Y     -2.16933540
12 2009-01-02 Y      0.58717501
13 2009-01-03 Y     -1.47955590
14 2009-01-04 Y     -0.43944637
15 2009-01-05 Y      2.26715032
16 2009-01-06 Y      1.69658999
17 2009-01-07 Y      0.86736879
18 2009-01-08 Y     -0.84527498
19 2009-01-09 Y     -1.88463696
20 2009-01-10 Y      3.10653581
21 2009-01-01 Z      2.70729743
22 2009-01-02 Z      3.36505925
23 2009-01-03 Z      0.55102040
24 2009-01-04 Z     -0.19087669
25 2009-01-05 Z      5.02017382
26 2009-01-06 Z      6.71240306
27 2009-01-07 Z      1.42427700
28 2009-01-08 Z      4.03411626
29 2009-01-09 Z      2.76534679
30 2009-01-10 Z     -1.01398236

In [458]:
spread(data = saham.gather, key = 'saham', value = 'harga') 
# menyebar data hasil gather (kebalikan)

waktu      X           Y          Z         
1  2009-01-01 -0.73932297 -2.1693354  2.7072974
2  2009-01-02 -0.66060205  0.5871750  3.3650593
3  2009-01-03  0.52308703 -1.4795559  0.5510204
4  2009-01-04  1.03084445 -0.4394464 -0.1908767
5  2009-01-05  0.05471038  2.2671503  5.0201738
6  2009-01-06 -1.02139422  1.6965900  6.7124031
7  2009-01-07  0.62023365  0.8673688  1.4242770
8  2009-01-08  0.75474458 -0.8452750  4.0341163
9  2009-01-09 -1.18884672 -1.8846370  2.7653468
10 2009-01-10 -1.03766147  3.1065358 -1.0139824

In [459]:
# menggunakan spread() dengan operator pipe
saham.gather %>% spread(key = 'saham', value = 'harga')

waktu      X           Y          Z         
1  2009-01-01 -0.73932297 -2.1693354  2.7072974
2  2009-01-02 -0.66060205  0.5871750  3.3650593
3  2009-01-03  0.52308703 -1.4795559  0.5510204
4  2009-01-04  1.03084445 -0.4394464 -0.1908767
5  2009-01-05  0.05471038  2.2671503  5.0201738
6  2009-01-06 -1.02139422  1.6965900  6.7124031
7  2009-01-07  0.62023365  0.8673688  1.4242770
8  2009-01-08  0.75474458 -0.8452750  4.0341163
9  2009-01-09 -1.18884672 -1.8846370  2.7653468
10 2009-01-10 -1.03766147  3.1065358 -1.0139824

### `separate()`

Memisahkan satu kolom ke banyak kolom.

In [1]:
df <- data.frame(kol.baru = c('a.x', 'b.y', 'c.z'))
df

kol.baru
1 a.x     
2 b.y     
3 c.z

In [5]:
separate(df, kol.baru, c("ABC", "XYZ"))

ABC XYZ
1 a   x  
2 b   y  
3 c   z

In [6]:
df <- data.frame(kol.baru = c('a-x', 'b-y', 'c-z'))
df

kol.baru
1 a-x     
2 b-y     
3 c-z

In [7]:
separate(df, kol.baru, c("ABC", "XYZ"))

ABC XYZ
1 a   x  
2 b   y  
3 c   z

In [8]:
# Sintaks lengkapnya:
separate(data = df, col = kol.baru, c('Pertama', 'Kedua'), sep="-")

Pertama Kedua
1 a       x    
2 b       y    
3 c       z

### `unite()`

Merupakan kebalikan dari `separate()`. Digunakan untuk menggabungkan kolom.

In [10]:
df1 <- separate(data = df, col = kol.baru, c('Pertama', 'Kedua'), sep="-")
df1

Pertama Kedua
1 a       x    
2 b       y    
3 c       z

In [11]:
# menggabungkan jd 1 kolom
unite(df1, kol.gab.baru, Pertama, Kedua, sep = '-')

kol.gab.baru
1 a-x         
2 b-y         
3 c-z